version: '3.8'

services:
  parking-db:
    image: postgres:15-alpine
    container_name: parking_postgres_container
    environment:
      POSTGRES_DB: parking_db
      POSTGRES_USER: parking_user
      POSTGRES_PASSWORD: dev12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_parking_data:/var/lib/postgresql/data

volumes:
  postgres_parking_data: